-- Advanced Group Management System
-- This migration adds group leader and attendance tracking features

-- 1. Add leader_id to groups table
ALTER TABLE groups 
ADD COLUMN IF NOT EXISTS leader_id BIGINT REFERENCES members(id) ON DELETE SET NULL;

-- Add comment to document the column
COMMENT ON COLUMN groups.leader_id IS 'Foreign key to members table - identifies the group leader';

-- 2. Create attendance table
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL CHECK (status IN ('present', 'absent')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  -- Ensure one attendance record per member per group per date
  UNIQUE(group_id, member_id, date)
);

-- Add comments to document the table
COMMENT ON TABLE attendance IS 'Tracks member attendance for group meetings';
COMMENT ON COLUMN attendance.group_id IS 'Foreign key to groups table';
COMMENT ON COLUMN attendance.member_id IS 'Foreign key to members table';
COMMENT ON COLUMN attendance.date IS 'Date of the attendance record';
COMMENT ON COLUMN attendance.status IS 'Attendance status: present or absent';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_attendance_group_id ON attendance(group_id);
CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;

-- Optional: Create a view for attendance summary
CREATE OR REPLACE VIEW attendance_summary AS
SELECT 
  g.id as group_id,
  g.name as group_name,
  a.date,
  COUNT(*) FILTER (WHERE a.status = 'present') as present_count,
  COUNT(*) FILTER (WHERE a.status = 'absent') as absent_count,
  COUNT(*) as total_count
FROM groups g
LEFT JOIN attendance a ON g.id = a.group_id
GROUP BY g.id, g.name, a.date;

COMMENT ON VIEW attendance_summary IS 'Summary view of attendance by group and date';
