-- Create Prayer Requests System
-- This migration creates the prayer_requests table for managing prayer requests

-- Create prayer_requests table
CREATE TABLE IF NOT EXISTS prayer_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'prayed')),
  visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comments to document the table
COMMENT ON TABLE prayer_requests IS 'Stores prayer requests submitted by members';
COMMENT ON COLUMN prayer_requests.member_id IS 'Foreign key to members table - who submitted the request';
COMMENT ON COLUMN prayer_requests.title IS 'Title/subject of the prayer request';
COMMENT ON COLUMN prayer_requests.message IS 'Detailed prayer request message';
COMMENT ON COLUMN prayer_requests.status IS 'Status: new or prayed';
COMMENT ON COLUMN prayer_requests.visibility IS 'Visibility: public or private';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_prayer_requests_member_id ON prayer_requests(member_id);
CREATE INDEX IF NOT EXISTS idx_prayer_requests_status ON prayer_requests(status);
CREATE INDEX IF NOT EXISTS idx_prayer_requests_visibility ON prayer_requests(visibility);
CREATE INDEX IF NOT EXISTS idx_prayer_requests_created_at ON prayer_requests(created_at DESC);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE prayer_requests DISABLE ROW LEVEL SECURITY;
