-- Create Notifications System
-- This migration creates the notifications table for comment notifications

-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  bible_study_id BIGINT REFERENCES bible_studies(id) ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comments to document the table
COMMENT ON TABLE notifications IS 'Stores notifications for users (e.g., new comments on Bible studies)';
COMMENT ON COLUMN notifications.user_id IS 'Foreign key to members table - who receives the notification';
COMMENT ON COLUMN notifications.message IS 'Notification message text';
COMMENT ON COLUMN notifications.bible_study_id IS 'Optional foreign key to bible_studies - for navigation';
COMMENT ON COLUMN notifications.is_read IS 'Whether the notification has been read';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, is_read);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
