-- Create groups table if it doesn't exist
CREATE TABLE IF NOT EXISTS groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Disable Row Level Security (RLS) for development
-- For production, create proper policies instead
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;

-- Optional: Allow anyone to insert groups (for development)
-- CREATE POLICY "Allow insert" ON groups
--   FOR INSERT WITH CHECK (true);

-- Optional: Allow anyone to select groups (for development)
-- CREATE POLICY "Allow select" ON groups
--   FOR SELECT USING (true);
