-- Create Bible Studies System
-- This migration creates the bible_studies table for managing Bible study content

-- Create bible_studies table
CREATE TABLE IF NOT EXISTS bible_studies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  verses TEXT NOT NULL,
  notes TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comments to document the table
COMMENT ON TABLE bible_studies IS 'Stores Bible study posts created by admins';
COMMENT ON COLUMN bible_studies.title IS 'Bible topic or study title';
COMMENT ON COLUMN bible_studies.verses IS 'Bible verses referenced in the study';
COMMENT ON COLUMN bible_studies.notes IS 'Main teaching content and explanation';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_bible_studies_created_at ON bible_studies(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bible_studies_title ON bible_studies(title);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE bible_studies DISABLE ROW LEVEL SECURITY;
