-- Create Events & Schedule System
-- This migration creates the events table for church event management

-- Create events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  event_type TEXT NOT NULL,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comments to document the table
COMMENT ON TABLE events IS 'Stores church events and schedules';
COMMENT ON COLUMN events.title IS 'Event title/name';
COMMENT ON COLUMN events.description IS 'Detailed description of the event';
COMMENT ON COLUMN events.event_type IS 'Type of event (Sunday Service, Prayer Meeting, etc.)';
COMMENT ON COLUMN events.event_date IS 'Date and time of the event';
COMMENT ON COLUMN events.location IS 'Location where the event will be held';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
