-- Create Comments System for Bible Studies
-- This migration creates the comments table for discussion under Bible study posts

-- Create comments table
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bible_study_id BIGINT NOT NULL REFERENCES bible_studies(id) ON DELETE CASCADE,
  member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  comment TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comments to document the table
COMMENT ON TABLE comments IS 'Stores comments/discussions for Bible study posts';
COMMENT ON COLUMN comments.bible_study_id IS 'Foreign key to bible_studies table - which study this comment belongs to';
COMMENT ON COLUMN comments.member_id IS 'Foreign key to members table - who posted the comment';
COMMENT ON COLUMN comments.comment IS 'The comment text content';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_comments_bible_study_id ON comments(bible_study_id);
CREATE INDEX IF NOT EXISTS idx_comments_member_id ON comments(member_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);

-- Disable Row Level Security for development
-- For production, create proper policies instead
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
